### ISSUE TITLE
Ignore large inboxes

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#101]
Let's find a way to ignore/skip over large inboxes (directories with more than 50K emails, say), for performance reasons.  Hopefully we won't miss out on any spear phishing attacks this way, and it should speed things up and cut down memory consumption a lot.

Need to think about how to do this, and at what phase.  We don't want to read in an Inbox object from file and then use `len(inbox)`, because it may take hours just to read in from disk.  Perhaps we can check the file length, or use `wc -l` to count the number of lines?

**Comment by MatthewChow** [comment]
One potential alternative that we were thinking about was this: instead of completely ignoring large inboxes, we can instead truncate the amount of data we are using by sampling from the large inboxes. For example, we can impose a limit of 100,000 emails used per sender (which would correspond to about 1 GB of memory based off of our current results), and only use these 100,000 emails when creating sender profiles and the training data matrix. If the original inbox had 1,000,000 emails, we would just sample every 10th email to use. If the original inbox had 500,000 emails, we would sample every 5th email to use. Under this approach, we still incur the time needed to read from disk, but we'll have a guarantee on the maximum memory consumption and time consumption.

Thoughts?

**Comment by davidwagner** [comment]
That seems like a plausible direction, too.  Seems like either one could work.

I'm not sure there's much to be gained by analyzing emails from those inboxes.  I have a suspicion that emails from those senders are less likely to be target for spear phishing, because those senders are uninteresting (e.g., Google Calendar event reminders, or spam, or something like that, which attackers probably won't try to fake in a targeted spear phishing campaign).  If that's true, then there's probably no point in looking at any of those emails.  I'll ask Vern to take a look, based on the ICSI data, and maybe that will help us choose between these two options.

**Comment by davidwagner** [comment]
Given Vern's email today, it sounds like we can just ignore those inboxes.  That'll be simpler, and faster.

Does that sound good?  What's your take?

**Comment by MatthewChow** [comment]
Agreed. Will set the initial threshold to ignore inboxes with more than 50k emails, and then adjust the threshold later on as needed.
