### ISSUE TITLE
Put simulated phishing into right directory

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#11]
Store the simulated phishing emails into the correct directory.

**Comment by mikeaboody** [comment]
The simulated phishing emails (from the mbox_to_file_structure.py script) were placed in the correct directory. However, it was issue 12 that was causing our problems.

**Comment by mikeaboody** [comment]
I actually misread Issue 12. Issue 12 is not relevant to why our false alarm rates were so high. However, instead it was that when we were storing the simulated phishing email into a random sender's directory, we were not also updating the From header of that sender when we were placing it in that directory. That has been fixed in 805ef64e27b65f684e9234641b8f22fe2cf43654
