### ISSUE TITLE
Crash in test_and_report() when calling reshape()

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#114]
We encountered the following crash:

      File ".../phishing-research/common/classify.py", line 202, in test_and_report
        test_mess_id = data['message_id'].reshape(sample_size, 1).astype("S200")
    ValueError: total size of new array must be unchanged

Possible theories:

It looks like this has something to do with the 'message_id' column in the test matrix not being the right size.

I'm wondering if maybe this could be caused by an email that doesn't have a Message-ID field.  I'm guessing that we'll get a None value in the test matrix, per the following line in generate_features.py generate_test_matrix():

            test_mess_id[row_index] = test_mbox[i]["Message-ID"]

Could that be the problem?  Maybe it's worth creating a test case that will test that situation?

Or could it be something else?

If you can't figure it out, can you add some debugging code to detect this situation and output some relevant information when it does happen to make it easier to debug?

**Comment by nexusapoorvacus** [comment]
I don't think the problem is a missing Message-ID field because when I tested the code on my inbox, I encountered multiple emails that did not have a Message-ID field and  I do not get a crash in test_and_report.

The test_mess_id array and test_data_matrix arrays in generate_text_matrix are both initialized using np.empty and test_data_matrix.shape[0] == test_mess_id.shape[0]. The sample_size value in test_and_report in classify should equal test_data_matrix.shape[0] (test_X.shape[0] in classify), and therefore should also be equal to test_mess_id.shape[0] (data['message_id'] in classify). So, I am not too sure why sample_size and data['message_id'].shape[0] are not equal.

For now, I have added a check in generate_test_matrix that sets test_mess_id[row_index] to "None" (a string) if the email does not have a Message-ID field. I also added a try-except block around test_mess_id = data['message_id'].reshape(sample_size, 1).astype("S200"). If a ValueError occurs, the actual length of data['message_id'] and sample_size printed. The data['message_id'] is also printed. I don't think we will be allowed to see data['message_id'], but perhaps Vern can see something of interest and let us know. Is there anything else that we should print?

The commit can be found here: 44fbe9c440176f5dc9efe3d74bd154cf9be8cdf8

**Comment by davidwagner** [comment]
Fixed by commit 8ad7663e12
