### ISSUE TITLE
Don't use same sender when generating simulated phish

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#12]
When generating a simulated phishing email, when you pick a new sender, explicitly check to make sure that the replacement sender is not the same as the original sender (if it is, choose another replacement sender randomly).

**Comment by MatthewChow** [comment]
This might be difficult to accomplish due to the following constraint:
If a sender has sent 10 legitimate emails, we want to ensure that we generate 10 pseudo-phish emails for that sender. If we're choosing replacement senders randomly instead of in a deterministically shuffled order, there is no guarantee that the number of legitimate per sender and the number of phish per sender are equal.

**Comment by davidwagner** [comment]
I guess I don't know the design of how you generate replacement senders, so hard to say how to fix it.

One possible fix: if replacement sender = original sender, don't generate a pseudo-phish.  We might generate slightly fewer pseudo-phish emails than legitimate emails, but seems OK.  Would that work, or does it violate other assumptions that were made elsewhere?

(Alternatively: Would it be easy to generate 2x as many replacement senders and shuffle the 2x list, and then when choosing a replacement sender, keep pulling the next sender until you find one that is different from the original sender?)

(Fallback: A possible short-term workaround: count how many of pseudo-phish messages were "bad" (used the same sender), as a diagnostic.)

**Comment by davidwagner** [comment]
Checking back in on this one...  Any feasible fixes?
