### ISSUE TITLE
Bug in Received headers mail path construction?

### ISSUE THREAD

**Issue by davidwagner** [mikeaboody/phishing-research#31]
If I understand the `received_headers.py` code correctly, it looks like it is generating the mail path incorrectly.

A mail path should look something like `[1.2.3.0/24, 5.6.7.128/25, 6.6.0.0/16]`.  However, it looks like the code is currently generating a list like `[24, 25, 16]`.

Looking at Lookup.getCIDR(), it looks to me like Lookup.getCIDR(1.2.3.4) returns something like 24, not 1.2.3.0/24. Looking at createReceivedHeaderSequences() and classify(), it looks to me like the thing you're adding to the profile is the list [24, 24, 18] rather than [1.2.3.4/24, 1.2.3.4/24, 5.6.7.8/18].

Check my reasoning.  I might be misinterpreting what I'm reading.

**Comment by mikeaboody** [comment]
I'll take a look at this later today.

**Comment by nexusapoorvacus** [comment]
I will take a look at it too. Since we made the whois lookups offline, we ended up returning the number of network bits since that number and the actual IP address gives us the CIDR block we need. But we should make sure that we are using this properly.

**Comment by nexusapoorvacus** [comment]
Prof. Wagner, you were correct in that the sequences were being stored by their cidr prefix (24 not 1.2.3.0/24 like you mentioned before). To fix this in the offline mode, I modified the getCIDR() method in lookup.py so that it returns the binary representation of the network portion of the IP address. 

For example, if the IP address is 1.2.3.4 and the cidr block it belongs in is a /24, getCIDR() returns "000000010000001000000011". Note that this string is 24 characters long since only the network portion is returned. Below is an example of a sample mail path

[000000010000001000000011, 000001010000011000000111000001011, 0000011000000110](Translates to: 1.2.3.0/24, 5.6.7.128/25, 6.6.0.0/16)

The reason this mail path should work is because all IP addresses in the same CIDR block should map to the same binary representation of the network portion of the IP address. I've made the changes on a different branch here: 7fe849b1fac5f9ee2e45f993a8b30f82e425d592
